name: propertystop
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.0.3
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  fl_chart: ^0.50.6
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  full_screen_image: ^1.0.2
  url_launcher: ^6.1.2
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  dio: ^4.0.6
  flutter_form_builder: ^7.2.1
  form_builder_file_picker: ^2.1.0
  loader_overlay: ^2.0.7
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.0
  gif_view: ^0.1.0
  video_player: ^2.4.5

dev_dependencies:
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/homeloan.jpg
    - assets/property_images/
    - assets/gifs/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
